def distinct_seq(a_min: int, a_max: int, b_min: int, b_max: int) -> int:
    """
    Calculate how many distinct terms are in the sequence generated by a**b
    :param a_min: Minimum value for a
    :param a_max: Minimum value for b
    :param b_min: Maximum value for a
    :param b_max: Maximum value for b
    :return: Sum of distinct terms
    """
    res_set = set()
    for a in range(a_min, a_max+1):
        for b in range(b_min, b_max+1):
            res_set.add(a**b)
    return len(res_set)


if __name__ == '__main__':
    print(distinct_seq(a_min=2, a_max=100, b_min=2, b_max=100))
